Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [3]:
import numpy as np
r=np.random.normal(size=25)
print(r)

[-2.74803499  0.19483683 -0.49259548  1.69393042 -1.1756506  -1.22232118
 -0.81366985 -0.05888874  0.13752706 -0.37870313  1.00973049 -0.79020317
 -1.37419193  2.58457798  0.26648781 -0.03512292 -0.13035745  0.11430495
 -2.69160828 -0.1459305   0.78063269  0.39218207 -0.24926071 -0.48135181
 -0.63904996]


Create an array of 20 linearly spaced points between 0 and 1

In [5]:
s=np.linspace(0,1,20)
print(s)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


Declare a numpy array of values from 1 to 100 and make it into a 10*10 matrix.

In [6]:
a=np.arange(1,101).reshape(10,10)
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


Using the previously defined matrix print rows 1,5,6

In [23]:
print(a[0])
print(a[4])
print(a[5])

[ 1  2  3  4  5  6  7  8  9 10]
[41 42 43 44 45 46 47 48 49 50]
[51 52 53 54 55 56 57 58 59 60]


Using the previously defined matrix print elemnts from 3rd row  to 10th row

In [24]:
l=len(a)
for i in range(2,l):
    print(a[i])

[21 22 23 24 25 26 27 28 29 30]
[31 32 33 34 35 36 37 38 39 40]
[41 42 43 44 45 46 47 48 49 50]
[51 52 53 54 55 56 57 58 59 60]
[61 62 63 64 65 66 67 68 69 70]
[71 72 73 74 75 76 77 78 79 80]
[81 82 83 84 85 86 87 88 89 90]
[ 91  92  93  94  95  96  97  98  99 100]


Using the previously defined matrix print all elemtnts from 4th column to 8th column

In [25]:
print(a[:,3])
print(a[:,7])

[ 4 14 24 34 44 54 64 74 84 94]
[ 8 18 28 38 48 58 68 78 88 98]


Using the same matrix print values from 3rd row 2nd coumn to 5th row 8th column

In [26]:
print(a[2:6,1:8])

[[22 23 24 25 26 27 28]
 [32 33 34 35 36 37 38]
 [42 43 44 45 46 47 48]
 [52 53 54 55 56 57 58]]


write a code to generate a 1000 random numbers each in the range(0,1) such that the count of all random points like are almost same.

In [33]:
b=np.random.normal(0,1,1000)
print(b)

[ 1.01693836e+00  4.04646078e-01 -3.59894529e-01  1.82483592e+00
 -1.04408883e+00 -1.25381111e+00  1.26753743e+00  1.39877298e+00
  1.45411846e+00 -7.07870669e-01  3.57146885e-01 -9.22689774e-02
  6.30943048e-01 -9.04004681e-01 -9.08314029e-02 -4.87400138e-01
  2.20993892e-01  5.05420442e-01 -2.70693486e-02  9.37514853e-01
  6.20973715e-01 -2.85081020e+00 -1.29446912e-01  8.08293619e-01
 -1.01174905e+00  2.09164136e-01 -3.73574315e-01  1.95493022e+00
 -1.78304356e+00  1.25277540e-02 -4.77397944e-01 -1.72283753e-01
  8.37321413e-01 -2.48306889e-02  1.24650979e+00 -2.32099291e-01
  1.14092098e+00 -5.32135423e-01 -3.56002889e-01 -1.76619448e-01
  3.05773021e-01  9.75900677e-01  1.51391706e+00 -3.88090808e-01
  1.84473863e+00 -2.61174114e-01 -5.56215878e-01  5.59255042e-01
 -8.71041071e-01  2.29973969e-01  8.11510581e-01 -6.45254042e-01
 -1.16994654e+00 -4.32009289e-01  5.63914988e-01  3.52614183e-01
  1.38770338e+00 -8.45144248e-01 -1.61608403e+00  1.97481036e-01
 -3.03884035e-01 -3.16488

write the commands to get standard deviation, mean ,mode,median for a given vector 

In [35]:
c=np.arange(1,6)
print(c)

[1 2 3 4 5]


In [36]:
print("Mean:",np.mean(c))

Mean: 3.0


In [37]:
print("Standard deviation:",np.std(c))

Standard deviation: 1.4142135623730951


In [40]:
print("Median:",np.median(c))

Median: 3.0
